[build]
  publish = "build"
  command = "npm run build"

# Proxy API
[[redirects]]
  from = "/api/*"
  to = "https://studentaccommodation.onrender.com/api/:splat"
  status = 200
  force = true

# React SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
